# Dynamic configuration for Traefik

http:
  middlewares:
    # Security headers middleware
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        contentSecurityPolicy: "default-src 'self'; frame-ancestors 'self'"

    # Rate limiting middleware
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1m

    # Basic authentication for dashboard
    dashboard-auth:
      basicAuth:
        users:
          - "admin:$apr1$ruca84Hq$mbjdMZBAG.KWn7vfN/SNK/"  # admin/password - CHANGE THIS!

  # Define routers and services here
  routers:
    dashboard:
      rule: "Host(`traefik.example.com`)"
      service: api@internal
      middlewares: 
        - dashboard-auth
        - security-headers

    # Example service
    whoami:
      rule: "Host(`whoami.example.com`)"
      service: whoami
      middlewares:
        - security-headers
        - rate-limit

  services:
    # Example backend service (replace with your actual services)
    whoami:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8080"
