http:
  routers:
    proxmox-web:
      rule: "Host(`pvx.example.com`) && PathPrefix(`/`)" ##Change the url
      service: "proxmox"
      middlewares:
        - "proxmox-headers"
    proxmox-api:
      rule: "Host(`pvx.example.com`) && PathPrefix(`/api2/`)" ##Change the url
      service: "proxmox"
      middlewares:
        - "proxmox-api-headers"
  services:
    proxmox:
      loadBalancer:
        passHostHeader: true
        serversTransport: "proxmox-transport"
        servers:
          - url: "https://xxx.xxx.xx.xx:8006" ##Change the ip address
  middlewares:
    proxmox-headers:
      headers:
        customRequestHeaders:
          X-Requested-With: "XMLHttpRequest"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        accessControlAllowCredentials: true
    proxmox-api-headers:
      headers:
        customRequestHeaders:
          X-Requested-With: "XMLHttpRequest"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "*"
        accessControlExposeHeaders:
          - "*"
        accessControlMaxAge: 3600
        accessControlAllowCredentials: true
  serversTransports:
    proxmox-transport:
      insecureSkipVerify: true
      serverName: "pvx.example.com"
