ttp:
  routers:
    uptimekuma:
      rule: "Host(`upt.example.com`)" # Change your domain
      service: "uptimekuma"
      middlewares:
        - uptimekuma-headers
  
  services:
    uptimekuma:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.xx.xx:3001" # Change your lxc ip
  
  middlewares:
    uptimekuma-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          Connection: "keep-alive"
          Access-Control-Allow-Origin: "*"
          Access-Control-Allow-Methods: "GET, PUT, POST, DELETE, OPTIONS"
          Access-Control-Allow-Headers: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
